version: '3'

services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
    ports:
      - "80:3000"
    volumes:
      - ./client:/app
    depends_on:
      - familiar-server
    environment:
      - REACT_APP_API_URL=http://server:5000  # Set the Flask API URL

