version: '3'

services:
  fyp-server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - fyp-client

  fyp-client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_API_URL=http://flask-server:5000  # Set the Flask API URL

